### DISCUSSION TITLE
Individual admixture computation

### DISCUSSION THREAD

**Discussion by alxsimon** [tskit-dev/tskit#2138] [Q&A] [answered]
Hi everyone,

I am new to treesequences and started playing with some simulations where I create the model in Demes -> run in Slim -> produce TreeSequences and recapitate.
For instance I did a simple simulation of a 2 populations split with divergence, followed by the formation of an admixed population in the last 100 generations.
For instance:
```
description: Admixture between two populations - Sim 1 no migration
time_units: generations
generation_time: 30
demes:
- name: ancestral
  epochs:
  - {end_time: 100000.0, start_size: 5000}
- name: Pop_A
  ancestors: [ancestral]
  epochs:
  - {end_time: 100, start_size: 100}
  - {end_time: 0, start_size: 10000}
- name: Pop_B
  ancestors: [ancestral]
  epochs:
  - {end_time: 100, start_size: 100}
  - {end_time: 0, start_size: 10000}
- name: Pop_C
  start_time: 100
  ancestors: [Pop_A, Pop_B]
  proportions: [0.4, 0.6]
  epochs:
  - {end_time: 0, start_size: 100}
```

One of the thing I have a hard time to figure out right now is how to compute the admixture composition of each individual.
Could you point me to resources or tutorials that exist on that? 
I feel like the [introgression tutorial](https://tskit.dev/tutorials/introgression.html) is close to what I want but I did not find an option in Slim equivalent to the msprime `record_migration`.

Or let me know if this is not possible at this time in tskit without using mutations to identify parental populations.

Thanks a lot,
Alexis
